### ISSUE TITLE
[enhancement] seeding scripts

### ISSUE THREAD

**Issue by ewong-btig** [oscarli916/full-stack-rbac#7]
seeding scripts should not have dependencies on service(`crud.rbac`). it should be directly interacting with ORM or SQL connection instance. 

service would be the place for implement some checking, rules, filters, caching for better data control.
other parts looks good for me.

see u on 13/2/2023 monday;)

**Comment by oscarli916** [comment]
I have removed dependencies on the seeding scripts. you can check it.

see you later :)
